name: Selenium Tests on Development
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Install Chrome and Firefox
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable firefox
      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2
      - name: Set up GeckoDriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
          tar -xzf geckodriver-v0.33.0-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/
      - name: Run Selenium Tests
        run: mvn test -Dselenium.headless=true
